### ISSUE TITLE
weheat blackbird heatpump not receiving room or target temp

### ISSUE THREAD

**Issue by inediblepotato** [Laxilef/OTGateway#180]
Hi folks/Laxilief, 
Up to recently I've using OTGateway on my remeha CV boiler and it was working great. Thanks again.

I have now replaced the boiler with a weheat blackbird P60 heatpump, all electric. They (weheat) officially support opentherm but I am having trouble getting OTGateway to work with it. Perhaps you can point me at a good place to debug it, I'd like to contribute, and maybe get the OTGateway listed on their site of compatible thermostats as others may benefit.

The weheat system has a webportal which allows to test the connection to the thermostat. Initially it says everything is working correctly but about 20mins later it says "We detected your OpenTherm thermostat, but it is not giving a room temperature or desired room temperature."

I tried all the troubleshooting OT suggestions. duplicate to CH2, summer/winter etc. but Ive not yet been successful. 
Ive disabled the OT option "Sync max heating temp with target temp" as that was also throwing telnet errors.

I disabled the sensors it doesnt support, exhaust temp, pressure, and even though it reports the DHW values, the weheat system does not yet allow OT to set the desired temp so i disabled DHW too so I could inspect the telnet logs without extra errors. 

For simplicity I have PID enabled but equitherm disabled. The indoor temp is being published via the homeassistant automation and it updating and working correctly, I can see it in the dashboard of OTGateway and in homeassistant. 

To test, I used my old remeha isense thermostat which worked, and I also reflashed the D1mini32 im using to the DIYLess original firmware which also works, the weheat system doesnt complain (tested over multiple days). I inspected the mqtt published opentherm messages on both the DIYLess and the OTGateway to see if I could see the difference. I can see that for the OTGateway under indoor_temp->set ={} , where this was a value when using the DIYLess firmware. 

Heres the MQTT opentherm messages (grabbed from MQTT explorer)
```
state = {"slave":{"memberId":64,"flags":93,"type":1,"appVersion":1,"protocolVersion":1,"connected":true,"flame":false,"cooling":false,"modulation":{"min":15,"max":0},"power":{"min":1.5,"max":10},"heating":{"active":false,"minTemp":20,"maxTemp":30},"dhw":{"active":false,"minTemp":30,"maxTemp":60},"fault":{"active":false,"code":0},"diag":{"active":false,"code":0}},"master":{"heating":{"enabled":true,"blocki…
settings = {"heating":{"enabled":true,"turbo":false,"target":19.3,"hysteresis":0.5,"turboFactor":7.5,"minTemp":21,"maxTemp":30,"maxModulation":75,"overheatProtection":{"highTemp":40,"lowTemp":10},"freezeProtection":{"lowTemp":10,"thresholdTime":600}},"dhw":{"enabled":true,"target":40,"minTemp":30,"maxTemp":60,"maxModulation":100,"overheatProtection":{"highTemp":95,"lowTemp":90}},"equitherm":{"enabled":false,…
sensors
  heating_temp = {"connected":true,"signalQuality":100,"value":20.16}
  heating_return_temp = {"connected":true,"signalQuality":100,"value":21.934}
  heating_setpoint_temp = {"connected":true,"signalQuality":100,"value":21}
  dhw_temp = {"connected":false,"signalQuality":100,"value":53.137}
  dhw_flow_rate = {"connected":false,"signalQuality":100,"value":0}
  exhaust_temp = {"connected":false,"signalQuality":100,"value":0}
  pressure = {"connected":false,"signalQuality":100,"value":0}
  modulation_level = {"connected":true,"signalQuality":100,"value":0}
  power = {"connected":true,"signalQuality":100,"value":0}
  outdoor_temp = {"connected":true,"signalQuality":100,"value":14.395}
  indoor_temp = {"connected":true,"signalQuality":100,"value":19.7}
    set = {}
status = online
```

and heres the DIYLess version
```
state = {"slave":{"memberId":64,"flags":93,"type":1,"appVersion":1,"protocolVersion":1,"connected":true,"flame":false,"cooling":false,"modulation":{"min":15,"max":0},"power":{"min":1.5,"max":10},"heating":{"active":false,"minTemp":20,"maxTemp":30},"dhw":{"active":false,"minTemp":30,"maxTemp":60},"fault":{"active":false,"code":0},"diag":{"active":false,"code":0}},"master":{"heating":{"enabled":true,"blocki…
settings = {"heating":{"enabled":true,"turbo":false,"target":19.2,"hysteresis":0.5,"turboFactor":7.5,"minTemp":20,"maxTemp":30,"maxModulation":75,"overheatProtection":{"highTemp":40,"lowTemp":10},"freezeProtection":{"lowTemp":10,"thresholdTime":600}},"dhw":{"enabled":true,"target":40,"minTemp":30,"maxTemp":60,"maxModulation":100,"overheatProtection":{"highTemp":95,"lowTemp":90}},"equitherm":{"enabled":false,…
sensors
  heating_temp = {"connected":true,"signalQuality":100,"value":22.938}
  heating_return_temp = {"connected":true,"signalQuality":100,"value":25.68}
  heating_setpoint_temp = {"connected":true,"signalQuality":100,"value":20}
  dhw_temp = {"connected":true,"signalQuality":100,"value":53.316}
  dhw_flow_rate = {"connected":false,"signalQuality":100,"value":0}
  exhaust_temp = {"connected":false,"signalQuality":100,"value":0}
  pressure = {"connected":false,"signalQuality":100,"value":0}
  modulation_level = {"connected":true,"signalQuality":100,"value":0}
  power = {"connected":true,"signalQuality":100,"value":0}
  outdoor_temp = {"connected":true,"signalQuality":100,"value":17.469}
  indoor_temp = {"connected":true,"signalQuality":100,"value":19.69}
    set = {"value": 19.68}
status = online
```

I notice I can get it to temporarily send the indoor temp if I enable the "Native heating control" opentherm option but 20mins later I hit the same issue, and of course that's not the idea as the OTGateway should be the heating control in this example.

In the telnet logs, with other issues solved, the only useful message is "[OT][HEATING][WARN] Failed set target temp"

Any debugging suggestions or obvious mistakes? Or should I just start adding debug messages and recompiling?
Thanks again.

**Comment by Laxilef** [comment]
Hi,

> but about 20mins later it says "We detected your OpenTherm thermostat, but it is not giving a room temperature or desired room temperature."

Indeed, the project reports the current indoor and target indoor temperatures only when "Native Heating Control" is enabled. It is assumed that in this mode the boiler itself calculates the required heat carrier temperature to maintain the set target indoor temperature.

> For simplicity I have PID enabled but equitherm disabled. The indoor temp is being published via the homeassistant automation and it updating and working correctly, I can see it in the dashboard of OTGateway and in homeassistant.

For testing, it is better to disable PID and Equitherm and simply change the temperature of the heat carrier.

> In the telnet logs, with other issues solved, the only useful message is "[OT][HEATING][WARN] Failed set target temp"

This means that the boiler is not accepting the target temperature of the heat carrier. It is possible that the temperature being set is lower than the minimum or higher than the maximum. Sometimes this can be due to the master member ID.

**Comment by Laxilef** [comment]
> It's a shame the DIYless firmware isn't open to inspect the code flow, also can't get the same telnet logs, only a serial output, which looks like hex.

The diyless website says you can connect using [OpenTherm Monitor](https://otgw.tclcode.com/otmonitor.html) to get useful information. This would help to understand what commands the diyless firmware sends to the boiler:
> **Enable OpenTherm serial output**
> Enables OpenTherm commands dump to the serial (micro-USB) port. You can use [OpenTherm Monitor](http://otgw.tclcode.com/otmonitor.html) software to monitor your setup. It allows you to inspect opentherm messages log and draw history graph to visualise system behavior. COM port is configured at baud rate of 9600bps.

Logs from the moment the boiler/esp was launched would help me.

**Comment by inediblepotato** [comment]
Apologies for the inactivity. work got busy and it took me a while to get platformio and visual studio working on linux (i was blocking too many required connections with opensnitch) 

> That is, in diyless you only have DHW enabled. Where do you see the heating working?
Given your explanation of the flags, I can see why this shouldn't work but yet the heating works with DIYLess firmware. When I raise the target room temp above the current room temp, the heatpump starts heating. I can see it in the weheat portal and in home assistant and the radiators get warmer. 

Got a chance to compile OTGateway today with the suggested line change in OpenThermTask.h and it appears to have had the desired effect.

The indoor room temp is now showing up in the weheat portal and so far it has not thrown an error after 20mins like before.
I appear to be able to set the target water temp. Also the PID and equitherm behaviour seem right. 

I will test it for a few days and report back.

The telnet logs still show warnings but the heatpump appears to be acting correctly.

`[00:40:18][OT][HEATING][WARN] Failed set current indoor temp
[00:40:19][OT][HEATING][WARN] Failed set target indoor temp
[00:40:19][OT][HEATING][WARN] Failed set max heating temp: 21.00 (converted: 21.00)
[00:40:19][OT][HEATING][WARN] Failed set target temp`

When the 'cooling support' option is enabled, telnet shows an additional warning, 

`Failed set cooling setpoint: 60% (response: 0%)`

But I have not tested the cooling further.  The cooling function of this heatpump is enabled but untested and is subject to a cooling test, which i dont know if its been performed. I have a low temp radiator due to be installed from the same company that supposedly allows the direct request for lower temperatures from the heatpump. I can test more once that is installed. 

Will report back after a few days of testing for the indoor temp reporting.
Thanks again.

**Comment by inediblepotato** [comment]
Hey @szrudi, no word from weheat yet.  They in general asked for more data so I'm collecting some. 

The changes have been working fine these last weeks. Having a little trouble tuning the PID but that's a normal separate PID thing with slow underfloor heating. 

I'll remove the native heating thing and update the PR but otherwise I can share the compiled changes if you want to test.

**Comment by inediblepotato** [comment]
Thanks @Laxilef, sorry I did reply, but github ate it. Will test the new master and get back to you.  My reply was along the lines of .... 

The weheat heatpump expects both the current RoomTemp and the RoomSetPoint. While it doesnt use the values it logs them in their portal/app and while there isn't anywhere in their portal/app to see warnings or errors about this type of thing, there is an opentherm connection test it performs each time you open the settings page and the control is set to opentherm. Here it can either state "thermostat is working perfectly", or "We detected your OpenTherm thermostat, but it is not giving a room temperature or desired room temperature."

I have observed that this warning doesn't always reflect a problem, as the current and desired room temp is visible (and changing/accurate) in their portal/app, and the behaviour of the heatpump is as expected... at least most of the time. 

So to answer the question directly, it needs both setRoomTemp and setRoomSetPoint.

...But while I thought I could just ignore the warning above, I have observed over a longer time period (days/weeks) that the heatpump occasionally doesn't behave as it should and I'm not sure why. I know this is probably better stated in a forum for the heatpump but Ill add it here to help figure it out for anyone with such a heatpump. 

If I plot the (heat carrier) target temp reported from the heatpump (via the home assistant integration), and the OTGateway heating setpoint, for the most part they agree over several days, with occasional disagreements when the heatpump stops heating the house and does its DHW cycle, so valid disagreements. Please ignore the swings in the actual temps in the attached plots, I've been playing with PID and auto fitting so the values are up and down. But what is important is the highlighted disagreements that if nothing has been restarted in several days, the heatpump seems to ignore the OTGateway setpoint value and does its own thing, possibly following it's heatcurve. No DHW cycle is running. In the weheat portal/app, there is no other indication of a problem besides the warning above, which is also present when the heatpump is behaving correctly. Restarting the OTGateway or the heatpump controller fixes the issue.

<img width="1898" height="401" alt="Image" src="https://github.com/user-attachments/assets/389878da-c94b-4986-904a-fe3250450659" />

For completeness I'm using the fork in PR #202 that sends both the current and set room temp. Only PID is enabled, no hysterisis or deadband, PIDmaxTemp=35, heating maxTemp=40, no equitherm.

The only thing I know to do is log the telnet output for a few days to see if there's any change in the output when this occurs. But anecdotally I don't see any difference when I check. I might make some debugging mqtt chatty logs so I can collect it directly in home assistant, it might help spot things. 

I have contacted weheat again. Will give them a chance to respond.

**Comment by Laxilef** [comment]
@inediblepotato Ok, thanks. I have another idea (dirty hack) that shouldn't break native OTC but will work with weheat. But we won't be able to use PID/Equitherm. If you simply set the target and current indoor temperature, will weheat maintain it?

**Comment by Laxilef** [comment]
I don't set version 4.2 because it requires significant changes to the library. Instead, I assume that boilers with the new opentherm 4.2 version should work correctly with a master device with version 2.2 (backward compatibility).

**Comment by un4g** [comment]
I have a weheat heat pump as well, and just ordered DIYLess to use it with it. Just stumbled upon this issue. Is this resolved with the latest update?

@inediblepotato

**Comment by szrudi** [comment]
> I have a heat pump as well, and just ordered DIYLess to use it with it. Just stumbled upon this issue. Is this resolved with the latest update?

I don't think it is fixed. As for me I've ended up using the DIYless hardware with ESPhome directly.

**Comment by un4g** [comment]
> > I have a heat pump as well, and just ordered DIYLess to use it with it. Just stumbled upon this issue. Is this resolved with the latest update?
> 
> I don't think it is fixed. As for me I've ended up using the DIYless hardware with ESPhome directly.
> 
> 

Good to hear there is at least some way to make it work. Do you mind sharing your config for esphome?

**Comment by inediblepotato** [comment]
The issue is still not fixed unfortunately.  The failures can take time to occur so needs a bit of focus which I did not have in the last while. 

The DIYless firmware works but closed source and lack of features and control etc. 

ESPHome software works, is open, and has more control but it's a bit of an Inconvenience to change things. It does however have an optional PID autotuner which is handy but is still difficult to tune well in a slow responding system (large dead time) like mine. The autotuner is just a package so can also be used in OTGateway. 

Tasmota works, is open, has options and an ok web interface but is still a little laborious to work with and the default features are a bit lacking. This works better if you put all the logic in home assistant (like one of the more complex thermostats) and just use the ESP32 to relay but I want something that will work even if home assistant isn't in the picture. 

I like the OTGateway, Laxilief has put in all the ground work, feels polished and the right balance to add options to tune things without reflashing which is why I'd still like to figure it out. 

Weheat updated their (read only) API twice in the last few months. I am certain there were Opentherm changes too as the report messages changed at the same time. But I have not seen a change in the behaviour for OTGateway.

As we enter summer I guess it will be more difficult to test. The cooling can be on but as of yet that is not controllable by the thermostat. I may have a way to trick that soon but it's not yet complete.

**Comment by un4g** [comment]
> The issue is still not fixed unfortunately. The failures can take time to occur so needs a bit of focus which I did not have in the last while.
> 
> The DIYless firmware works but closed source and lack of features and control etc.
> 
> ESPHome software works, is open, and has more control but it's a bit of an Inconvenience to change things. It does however have an optional PID autotuner which is handy but is still difficult to tune well in a slow responding system (large dead time) like mine. The autotuner is just a package so can also be used in OTGateway.
> 
> Tasmota works, is open, has options and an ok web interface but is still a little laborious to work with and the default features are a bit lacking. This works better if you put all the logic in home assistant (like one of the more complex thermostats) and just use the ESP32 to relay but I want something that will work even if home assistant isn't in the picture.
> 
> I like the OTGateway, Laxilief has put in all the ground work, feels polished and the right balance to add options to tune things without reflashing which is why I'd still like to figure it out.
> 
> Weheat updated their (read only) API twice in the last few months. I am certain there were Opentherm changes too as the report messages changed at the same time. But I have not seen a change in the behaviour for OTGateway.
> 
> As we enter summer I guess it will be more difficult to test. The cooling can be on but as of yet that is not controllable by the thermostat. I may have a way to trick that soon but it's not yet complete.

Thanks for a comprehensive overview. Surely if everything else (DIYless, ESPHome, Tasmota) works with weheat it must be a bug in OTGateway that it does not work with it, rather than how weheat handles opentherm

**Comment by szrudi** [comment]
> Good to hear there is at least some way to make it work. Do you mind sharing your config for esphome? 

Hey @un4g, here it is:

https://gist.github.com/szrudi/d519eb48d2e786afbb67ea97351c2ae4

Probably could be cleaned up a little but it works very nicely for me as it is.
